spring.application.name=hyperlocal

spring.datasource.url=jdbc:mysql://localhost:3306/hyperlocal
spring.datasource.username=root
spring.datasource.password=jenicadavid@02

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect